### ISSUE TITLE
Broken ya ide vscode-py

### ISSUE THREAD

**Issue by maximyurchuk** [yandex/yatool#9]
Hello,

I am trying to generate an ide project for [library](https://github.com/ydb-platform/ydb/tree/main/ydb/tools/ydbd_slice) and I get the following error: 

```
maxim-yurchuk@yurchuk-github:~/ydb/ydb/tools/ydbd_slice$ ~/ydb/ya ide vscode-py -P=~/sample
Generating venv: /home/maxim-yurchuk/sample/venv
Error[-WBadDir]: in $B/ydb/tools/ydbd_slice/_ya_venv_bdd0501f390c3a984e1e119af87a3619/libpy3yapython.a: PEERDIR to missing directory: $S/contrib/python/pip
Configure error (use -k to proceed)
```

It seems that like the open-source version of ya tool is missing some packages (`contrib/python/pip`)

**Comment by frazenshtein** [comment]
Hello! 

Sorry to be late with the reply. The specified module was indeed missing and was required to generate the project using `ya ide vscode-py` / `ya ide venv`. We have included it in our repo - https://github.com/yandex/yatool/tree/main/contrib/python/pip. However, in order for you to start generating a project for YDB, you need to contact the YDB maintainers so that they also add the specified module to their project.
